
experiment:
    type: lrm
    seed: 42
    parent: gobjaverse-2sides-large
    child: 0428_conv_e10

model:
    camera_embed_dim: 1024
    rendering_samples_per_ray: 128
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32                                                # always 32.
    triplane_high_res: 64                                               # useless?
    triplane_dim: 80
    encoder_type: dinov2
    encoder_model_name: dinov2_vitb14_reg
    encoder_feat_dim: 768
    encoder_freeze: false
    model_lora_rank: 4
    conv_fuse: True

dataset:
    subsets:
        -   name: gobjaverse_delete_tb
            root_dirs:
                ['data/data_gobjaverse_delete_tb']
            meta_path:
                train: data/data_gobjaverse_delete_tb/train.json
                val: data/data_gobjaverse_delete_tb/val.json
            sample_rate: 1.0
    sample_side_views: 3
    source_image_res: 336
    render_image:
        low: 128
        high: 384
        region: 128
    normalize_camera: true
    normed_dist_to_center: auto
    num_train_workers: 4
    num_val_workers: 2
    pin_mem: true

train:
    mixed_precision: fp16  # REPLACE THIS BASED ON GPU TYPE
    find_unused_parameters: false
    loss:
        pixel_weight: 1.0
        perceptual_weight: 1.0
        tv_weight: 5e-4
    optim:
        lr: 4e-4                                                        # most important.
        weight_decay: 0.05
        beta1: 0.9
        beta2: 0.95
        clip_grad_norm: 1.0
    scheduler:
        type: cosine
        warmup_real_iters: 3000
    batch_size: 2  # REPLACE THIS (PER GPU)
    accum_steps: 1  # REPLACE THIS
    epochs: 10  # REPLACE THIS
    debug_global_steps: null

val:
    batch_size: 4
    global_step_period: 1000
    debug_batches: null

saver:
    auto_resume: true
    load_model: 
        type: hugging_face
        url: zxhezexin/openlrm-mix-large-1.1/model.safetensors
    checkpoint_root: ./exps/checkpoints
    checkpoint_global_steps: 1000
    checkpoint_keep_level: 5
    load_model_func_kwargs: 
        strict: False

logger:
    stream_level: WARNING
    log_level: INFO
    log_root: ./exps/logs
    tracker_root: ./exps/trackers
    enable_profiler: false
    trackers:
        - tensorboard
    image_monitor:
        train_global_steps: 100
        samples_per_log: 4

compile:
    suppress_errors: true
    print_specializations: true
    disable: true

inferrer:
    logger: INFO
    hugging_face: False
    iteration: 13340
    image_format: True
    
    source_size: 448
    source_cam_dist: 2.0
    render_size: 384
    render_views: 16
    render_fps: 40
    frame_size: 2
    mesh_size: 1024
    mesh_thres: 1